### PR TITLE
Add support for detached elements with absolute positions

### PR DESCRIPTION
**Pull request by zaro**
I added a pos: {x: , y:} attribute for absolute positioning , I think this is what #12 is about.
I have no clue though, if the patch takes into account all possibilities , but it seems to work for me so far :)

### CODE REVIEW

**Comment by jthoenes** [comment]
Hi @zaro. Thanks for your effort. Looks good to me. I just have two wishes:

* Could you remove the build files from your patch? They make merging other pull requests harder. We typically only commit build files on releases.
* I would prefer ``absolutePosition`` to ``pos`` - simply because it is more explicit and the majority of pdfmake is relative positioned.

Have you checked how this logic behaves if you have multiple pages?

**Comment by zaro** [comment]
hi @jthoenes ,

Renamed to absolutePosition and reverted the build files.
The example in the patch creates 3 pages with, mostly absolutePosition  elements, and the pdf looks correct.

**Comment by jthoenes** [comment]
Has been merged manually. Thanks @zaro!

**Comment by bpampuch** [comment]
@zaro Thank you, great work !!!

**Comment by damiencuvillier** [comment]
This could be great !! 

Not yet pushed to bower repository ? 
In which version can I found it ?

**Comment by jthoenes** [comment]
It will be in the next release.
Am 16.03.2015 16:30 schrieb "Damien Cuvillier" <notifications@github.com>:

**Comment by damiencuvillier** [comment]
Do you know the release date ?

**Comment by jthoenes** [comment]
No, the build file will only be updated when there is actually a release. You can download the source from github and build the project yourself.

The releases are done by @bpampuch - we don't have a date set yet. But be patient. He is really busy and does this project in his free time.

**Comment by zaro** [comment]
@jthoenes Are there any instructions how to build ? Because just using the browserify task in the grunt file, produces unusable build/pdfmake.js, or unusable at least with an AMD loader (RequireJs in my case).

What happens is that when you require(['pdfmake'], function(pdfmake) { } )
The pdfmake object you get is actually the VFS wrapper module (defined in browser-extensions/virtual-fs.js) instead of pdfMake (browser-extensions/pdfMake.js) .

**Comment by damiencuvillier** [comment]
@jthoenes Thanks. I appreciate. Be sure I'm aware this is a freetime project. And congrats for the great job !
I got last upgrades directly in git yesterday night. I was not able to build app with grunt config (different issue). I had to include the fixes directly in the bower downloaded code. (same @zaro questions)

**Comment by jthoenes** [comment]
Ah, you're right. There seems to be something wrong in the grunt-browsify configuration. It happens when you introduce 5e68a5ddc89f7a4bf3e998b022208095021184cd - which was necessary because otherwise the ``grunt build`` fails on Linux (not on Mac, because Mac is case insensitive).

I'm not a grunt-browsify expert .. so help to fix it is greatly appreciated. I'll try to look deeper into it soon.

**Comment by zaro** [comment]
@jthoenes Will gladly help,if I had any clue where to start at :)

I played for several hours with browserify and grunt browserify, but couldn't find a way to produce working build. If I manage by tweaking settings to produce file that will return the correct module that has createPdf function, later when creating PDF, at some point exception is thrown that says : printer.fs.bindFS is not a function. 

All I could find was that possibly using brfs is an option, but it seemed like too much for me , given that this is the first time, I am using browserify and grunt . But maybe when I have some more time I'll give it another try.

**Pull request closed without merging**
