### PR TITLE
Add handle for undefined or null values

### PR DESCRIPTION
**Pull request by nicosevilla-github**

### CODE REVIEW

**Comment by liborm85** [comment]
Which issue fixes this PR?

**Comment by nicosevilla-github** [comment]
This PR fixes issues I encountered on those 2 files, I added a check on things where like for example an array or variable does have null or undefined values that causes pdf generator to error. 
See image.
screen shot 2018-05-28 at 2 32 44 pm

**Comment by liborm85** [comment]
It will be related to https://github.com/bpampuch/pdfmake/issues/1314 which was implemented by https://github.com/bpampuch/pdfmake/commit/216b189b9bd32719444484644a0f6a7bcc04d3cd.

**Comment by nicosevilla-github** [comment]
Thanks!

**Pull request closed without merging**
