### PR TITLE
Add logic to render a table of contents

### PR DESCRIPTION
**Pull request by jorgebo10**
Add a table of content:

Should add a required text element in document content with tocMarker flag set to true.
e.g.:

{
 text:"Table of context", //This is required, if not empty this will be used as the toc title, otherwise default TABLE OF CONTENT will be set
 tocMaker: true
}

Then in every text element that you want to include in the toc should add the toc flat set to true

{
 text: "Title 1",
 toc: true
}

{
 text: "Title 2",
 toc: true,
}

### CODE REVIEW

**Comment by aconran** [comment]
This is a cool feature idea.

It would be nice if each table of content line item was templateable (probably with a function similar to the header/footer). It would also be nice for them to be linkable in the pdf doc.

I am doing something similar for TOC generation although I have to do it afterwards via 2 passes since I concatenate multiple other documents. 1st pass to determine how long the actual TOC will be and 2nd pass to write the page numbers (because I count TOC pages as pages with page numbers)

**Comment by patrickdet** [comment]
@jorgebo10 woah this is quite nice! having a function like header/footer would definitely be good to have but this is already great

**Comment by miltador** [comment]
@jorgebo10,
Thanks for your contribution! This is a really good idea.
Though I think the API for this could be improved.

> {
text:"Table of context", //This is required, if not empty this will be used as the toc title, otherwise default TABLE OF CONTENT will be set
tocMaker: true
}

This block isn't really a text block, which can be confusing. Instead of flag `tocMaker: true` we could provide definition like this:
```js
{
  toc: {
    title: "Table of contents",
    // there we can add other options in future like making toc elements point to the actual text with link, etc
  }
}
```

**Comment by jorgebo10** [comment]
@miltador i like the approach you mention, i'll try to update the solution. Also i need to add some test and improve the code. Thanks for feedback

**Comment by liborm85** [comment]
@jorgebo10  Add some example to `examples` folder. Thanks.

**Comment by Diferno** [comment]
Hi, nice TOC implementation! 
Although it's not merged to master until conflicts are resolved, right?

If I could give my 2copper coins, it would be nice to propagate the style or inline attributes to toc element like:
  _//it would be great if styledictionary worked:
 // style: 'title1'
 // meanwhile I'm using inline styling_
`
{
toc: {
         title: 'My table of contents',       
         style: {
                fontSize: 22,
                bold: true,
                margin: [0, 0, 0, 20]
           }
     }
}`

And in layoutBuilder.js:
_// should take the styles from the styleDictionary or default
 ? docStructure[tocIndexPosition].toc.style : {bold: true, alignment: 'center', fontSize: 12, colSpan: 2, margin:[0, 0, 0, 20]}
_
`var style = docStructure[tocIndexPosition].toc.style;
docStructure[tocIndexPosition] = toc;
body = [];
if (style){
	body =  [[Object.assign({text: title, colSpan: 2}, style), {}]];
} else {
	body = [[{text: title, bold: true, alignment: 'center', fontSize: 12, colSpan: 2, margin:[0, 0, 0, 20]}, {}]];
}`

**Comment by liborm85** [comment]
This method of creating TOC building PDF twice, which is problematic on performance. I thinking of other eventuality.

My idea:
* First step: extract item for TOC (`tocItem: true`) from docDefinition
* Second step: from this array prepare table with pseudo page numbers
* Third step: prepared table insert insert into TOC (`toc: { }`) (we already know how many pages will have the TOC)
* Fourth step: and render PDF. While rendering TOC item (`tocItem: true`) replace pseudo page number with correct page number in TOC table.

I hope that my idea is correct and feasible...

**Comment by ssured** [comment]
@liborm85 I think you sum up a better (more efficient) strategy; but it also makes the implementation harder. Would it be possible to introduce this feature in 2 phases?

Phase 1: use double building, but make sure the engine only runs twice if there is a TOC. This will ship this much requested feature.

Phase 2: optimize the implementation using the 4 steps in your post, those sound very reasonable and make sure render times are in control

**Comment by liborm85** [comment]
I started  implementing TOC without twice rendering, see https://github.com/bpampuch/pdfmake/issues/126#issuecomment-298230195.

**Comment by ssured** [comment]
@liborm85 cool stuff!!

It's very nice to be able to push content through a 'wormhole' to another place in the document.

To be able to create a real TOC, with pagenumbers, something more needs to be added. Maybe a pageNumber text placeholder could work?

```
{
  text: { pageNumber: '00'}
}
```

At first render this will render with the supplied text `00`. After layouting the PDF the text will be replaced with the page number of the page where the the text was rendered.

Providing a default number makes sense to me, as the programmer will know how many pages will be likely. If you expect 1-9 pages, you'll provide `0`, if you expect 100-999 pages you'll provide `000` as a placeholder.

Next step would be to include pageMarkers in elements and be able to provide a reference to a marker. For this to work objects should be able to have an id, which can later be referenced. Something like this comes to mind:

```javascript
[
  // provide a TOC
  {
    toc: {
      name: 'mainIndex',
      title: {text: 'INDEX', style: 'header'}
    },
    pageBreak: 'after',
  },
...
  // some data in the document
  { text: 'TITLE', style: 'header', id: 'header1' },
  {
    text: [
      'TITLE', ' is printed on page ',
      {
        pageNumber: '00',
        pageNumberOf: 'header1'
      },
    ],
    tocItem: 'mainIndex',
  },
  'some text',
  'some more text',
}
```

`id` can be any string on an element. A hash is then an easy way to create a reference to all elements.

`pageNumberOf` determines of which element the pageNumber should be returned.

Thoughts?

**Comment by liborm85** [comment]
Continued here: https://github.com/bpampuch/pdfmake/issues/126

**Pull request closed without merging**
