### PR TITLE
Features: link, noWrap

### PR DESCRIPTION
**Pull request by ymkins**
Seems like people would like these features in upstream

https://github.com/bpampuch/pdfmake/issues/37

### CODE REVIEW

**Comment by hillelcoren** [comment]
+1

**Comment by ymkins** [comment]
Unfortunately I've duplicated 
https://github.com/bpampuch/pdfmake/pull/347
https://github.com/bpampuch/pdfmake/pull/361

**Comment by bpampuch** [comment]
thx

**Comment by uanthwal** [comment]
@bpampuch , Thanks for developing such an awesome lib, this library is really nice as compared to other libraries for doing this task. However, I am facing once issue with hyperlinks, please help me out with this. I want to add hyperlink to text. I have included :
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.20/pdfmake.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.20/vfs_fonts.js"></script>
I am using this in angular app. 
Thank you again

**Pull request closed without merging**
