### PR TITLE
fix(table): dontBreakRows not fitting on single page #1159

### PR DESCRIPTION
**Pull request by akyrey**
Should fix issue #1159 related to dontBreakRows that would completely remove the row if it would not fit on a single page

### CODE REVIEW

**Comment by liborm85** [comment]
Tested with example from https://github.com/bpampuch/pdfmake/issues/1159, but is same behavior. What was it supposed to fix?

**Comment by masterk63** [comment]
Hi, @akyrey I was testing, and yes fix my problem, works like a charm, could you please merged it, I gonna love it.

**Comment by akyrey** [comment]
@liborm85 sorry to reply a bit late. You are right, I tested my changes on the example from #1159 and it didn't work. I tried playing around a bit with that example and I found out that it works correctly if table layout is set to `noBorders`. That's probably why it works correctly on my environment and for @masterk63 

I'm gonna close current merge request since it is related to master branches and open a new one for branch 0.1

**Comment by akyrey** [comment]
Reopened as #2231

**Pull request closed without merging**
