### PR TITLE
introduce metadata and pass it to header/footer to e.g. reset page count

### PR DESCRIPTION
**Pull request by robstoll**
This change is actually not against master but against 0.17.1
https://github.com/bpampuch/pdfmake/compare/0.1.71...tegonal:metadata?expand=1

It solves https://github.com/bpampuch/pdfmake/issues/210
I am happy to add it to master if this approach suits you

### CODE REVIEW

**Comment by liborm85** [comment]
Tests failing. And you create PR with 208 commits in 116 files, this is wrong PR. Fix it.

**Comment by robstoll** [comment]
@liborm85 

> This change is actually not against master but against 0.17.1
https://github.com/bpampuch/pdfmake/compare/0.1.71...tegonal:metadata?expand=1

> It solves #210
> I am happy to add it to master if this approach suits you

I need a few pointers as master seems to be the upcoming 2.x release branch. Where go chsnges for 1.x?

**Comment by liborm85** [comment]
0.1 branch is for 0.1 version
master branch is for 0.2 version

**Comment by robstoll** [comment]
:+1: closing this PR, I'll create a new one once ported to the 0.1 branch

**Pull request closed without merging**
