### PR TITLE
Fixes for svg-to-pdfkit in the browser and fixes to svg size regexs and missing svgs in tables and headers

### PR DESCRIPTION
**Pull request by kwkelly**
This adds SVG-to-PDFkit as an external dependency in webpack config. Fixes https://github.com/bpampuch/pdfmake/issues/1794

Reverts and fixes https://github.com/bpampuch/pdfmake/pull/1790 which has a greedy regex and grabs too much if the viewBox is not at the end of the svg element

Adds fix for missing svg in headers and tables. Fixes https://github.com/bpampuch/pdfmake/issues/1797

### CODE REVIEW

**Comment by rabraha3** [comment]
I can confirm this bug in v2.0. I have not tested it in the 0.1 branch; the original issue tested v0.1.58.

In `elementWriter.addFragment`, should we change the switch...case statement to:

```javascript
case 'image':
case 'svg': // add this extra case, so method does not skip the SVG node
    var img = pack(item.item);

    img.x = (img.x || 0) + (useBlockXOffset ? (block.xOffset || 0) : ctx.x);
    img.y = (img.y || 0) + (useBlockYOffset ? (block.yOffset || 0) : ctx.y);

    page.items.push({
        type: item.type, // changed from 'image' --> will be either 'image' or 'svg'
            item: img
        });
    break;
```

The SVG and IMAGE cases have literally the same logic; just the "type" property in what is pushed to `page.items` is changed. And it always matches the `item.type` property. On the other hand, keeping the `svg` as a completely separate case allows for the two to diverge ... don't know if they ever will or not.

**Comment by rabraha3** [comment]
@kwkelly Awesome fix; I note the `CONTRIBUTING.md` says to

> **Please do not commit changes in build folder.**

¯\_(ツ)_/¯

**Comment by kwkelly** [comment]
> @kwkelly Awesome fix; I note the `CONTRIBUTING.md` says to
> 
> > **Please do not commit changes in build folder.**
> 
> ¯_(ツ)_/¯

In general I agree with that, but if I don't commit the changes to the build folder, then SVGs are still broken client side. @liborm85 can you weigh in here?

**Comment by liborm85** [comment]
@kwkelly Build folder is updated only when a new version is released. Revert changes in build folder.

**Comment by liborm85** [comment]
@kwkelly If is library svg-to-pdfkit builded in webpack only as "link" in externals, how make svg workable in browser now?

**Comment by blikblum** [comment]
Just add svg-to-pdfkit as a dependency in webpack projects or add as a script before pdfmake on standalone usage

**Comment by liborm85** [comment]
Yes theoretically only need to load svg-to-pdfkit first (according to https://webpack.js.org/configuration/externals/).

so like this:
```js
<script type="text/javascript" src="js/svg-to-pdfkit/source.js"></script>
<script type="text/javascript" src="js/pdfmake.js"></script>
<script type="text/javascript" src="js/vfs_fonts.js"></script>
```

But is returned error `Cannot find module 'svg-to-pdfkit'`. 
Probably library svg-to-pdfkit doesn't support this external loading.

**Comment by blikblum** [comment]
Yes It supports only commonjs. To support browser without a bundler will need to be patched to add an umd loader. 

But AFAICS this PR is correct

**Comment by liborm85** [comment]
PR is correct, but it doesn't work. hehehe, good.

**Comment by blikblum** [comment]
Works with webpack.

PR does that should do for an optional dependency. The issue is with svg-to-pdfkit. Is a easy fix

**Comment by rabraha3** [comment]
While this PR is for the `master` branch (v.2), I tested out the changed in the `0.1` branch, it it seemed to work -- I could display SVGs in headers, footers, and tables.

**Comment by liborm85** [comment]
Merged.

And svg-to-pdfkit is built-in in default by commit: https://github.com/bpampuch/pdfmake/commit/b50268035196a075a783296e73154081c36721d1

**Pull request merged**
