### PR TITLE
PDFKit bufferPages option added for better page management

### PR DESCRIPTION
**Pull request by andrewckor**

### CODE REVIEW

**Comment by andrewckor** [comment]
This feature is related to printer and gives you access to the page counter of PDFKit. It also lets you switch between pages on a PDFKit level.

```
// Switch to first page
pdf.switchToPage(pdf.bufferedPageRange().start);

// And draw a vector, logo
pdf.path('vector logo path');
```

**Comment by liborm85** [comment]
If is `bufferPages` enabled, this will cause problems with big memory usage for large files.
Better is draw everything items using pdfmake.

**Comment by andrewckor** [comment]
@liborm85 I updated my PR and moved bufferPages into printer options, take a look and let me know:
`var pdfKitDoc = printer.createPdfKitDocument(docDefinition, {bufferPages: true});`

**Comment by andrewckor** [comment]
@bpampuch can someone take a look?

**Comment by liborm85** [comment]
Merged.

**Comment by msroot** [comment]
+1

**Pull request merged**
