### PR TITLE
optimize qrcode

### PR DESCRIPTION
**Pull request by atiertant**
replace qrcode hundreds vectors by a svg path

### CODE REVIEW

**Comment by liborm85** [comment]
I tried generate [this QR example](https://github.com/bpampuch/pdfmake/blob/master/examples/qrCode.js) with your PR modifications but are displayed blank QR.

**Comment by atiertant** [comment]
thanks for review, i fixed it

**Comment by liborm85** [comment]
Now it works, but QR code "points" contains a shadow, see differences in image:
comparison

Generated pdf files:
[qrCode-original.pdf](https://github.com/bpampuch/pdfmake/files/1385245/qrCode-original.pdf)
[qrCode-svgpath.pdf](https://github.com/bpampuch/pdfmake/files/1385246/qrCode-svgpath.pdf)

I do not know why svg path creates this shadows, but it is not good for QR readers.

**Comment by liborm85** [comment]
Invalid, No reaction => Close

**Pull request closed without merging**
