### PR TITLE
Fix some problems parsing SVGs

### PR DESCRIPTION
**Pull request by sophistifunk**
Makes the SVG parsing slightly more robust to address #2021 

Branched from 0.1.66 tag.

### CODE REVIEW

**Comment by sophistifunk** [comment]
This isn't going to be as future-proof as switching to a proper XML parser, but it's an improvement on what's there.

**Comment by liborm85** [comment]
It really looks awful. I agree, it will be better to use library for parsing XML. PR is welcome.

**Comment by sophistifunk** [comment]
I've updated it again to use `xmldoc` which I've used in the past with a lot of success (for converting other kinds of documents).

I kept the public API for `SVGMeasure` the same (converting back to text before rendering), but in the future depending on your plans for the next version I would suggest copying the code from `svg-to-pdfkit`, removing its xml parser and using the same DOM structure for both measuring and converting to pdfkit calls.

**Comment by liborm85** [comment]
Merged. Thanks.

svg-to-pdfkit is package used for svg transformation to pdf, it is not possible to copy code from this package because is being developed by someone else.

**Pull request merged**
