### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by CorvusCorrax**
Use image headers to find width and height.
Generate qrcode as single SVG path instead of hundreds of rect vectors.
Progress callback now called during entire process (measure, layout processing and rendering).

### CODE REVIEW

**Comment by liborm85** [comment]
Why you remove definition of images over `docDefinition.images` ?

**Comment by atiertant** [comment]
`docDefinition.images` was used to store base64 images but as we convert them to buffer, we don't need it anymore

**Comment by liborm85** [comment]
Yes, `docDefinition.images` is used for store images in base64 and this is necessary feature in browser can not be removed.

Do not name one big PR with more things/features/changes, split it on qrcode, progress, etc.

**Comment by liborm85** [comment]
https://github.com/bpampuch/pdfmake/pull/1144, https://github.com/bpampuch/pdfmake/pull/1145

**Pull request closed without merging**
