### PR TITLE
Feature/0.1/superscript

### PR DESCRIPTION
**Pull request by rabraha3**
Most basic support for superscript/subscript. **Asking for comments**

Wondering if this would suffice for most applications. To support custom offsets would require more extensive updates to the style object.

1. "sup", "sub" style properties offset the text baseline by a fixed amount.
2. Users must manually set the font size _smaller_ for things to look "nice".

**Note**: text decorations (e.g., strikethroughs) do NOT follow the offset baseline. They follow the regular text inline y-position.

### CODE REVIEW

**Comment by rabraha3** [comment]
If we want to be able to specify the offset, that is possible. Just want to re-iterate that the decorations (underline / strikethrough) do NOT get moved up.

**Comment by liborm85** [comment]
Please examples of usage to [`/examples/styling_properties.js`](https://github.com/bpampuch/pdfmake/blob/0.1/examples/styling_properties.js). Thanks.

**Comment by liborm85** [comment]
It's too complicated to use, it should automatically reduce font size.

**Comment by SouengKimmeng** [comment]
Hello sir, could you help to review and merge this please. I really need that feature "sup", "sub"

**Comment by liborm85** [comment]
Finished in PR https://github.com/bpampuch/pdfmake/pull/2128.

**Pull request closed without merging**
