### PR TITLE
Fixes issue #1042

### PR DESCRIPTION
**Pull request by fe-cj**
Fixes [#1042](https://github.com/bpampuch/pdfmake/issues/1042)

It was not calculating correctly the 'y' at the end of a rowSpan with dontBreakRows.

### CODE REVIEW

**Comment by liborm85** [comment]
PR is in conflict with PR #2775.

**Comment by fe-cj** [comment]
Ok, will solve the conflicts later.

**Comment by fe-cj** [comment]
Done

**Comment by liborm85** [comment]
Cool. Merged. Thanks.

**Comment by fe-cj** [comment]
It also fixes [#2452](https://github.com/bpampuch/pdfmake/issues/2542)

**Comment by Phi-Hung-1007** [comment]
const ctxBeforeRowSpanLastRow = this.writer.contextStack[this.writer.contextStack.length - 1]; 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length') ?

**Comment by fe-cj** [comment]
@Phi-Hung-1007 Can you please share a doc definition that we can use on the [playground](http://pdfmake.org/playground.html) to reproduce the bug? Thanks.

**Comment by Phi-Hung-1007** [comment]
On the playground, I use dontBreakRows to avoid breaking rowspan between two pages but still get it, it seems like version 2.0.13 is not applied on playground yet?
Ảnh chụp màn hình 2024-09-27 211848

**Comment by Phi-Hung-1007** [comment]
On the playgound, I use dontBreakRows to avoid breaking rowspan between two pages but still get it, it seems like version 2.0.13 is not applied on playground yet?
image

**Comment by liborm85** [comment]
On playground is latest version 0.2.13.

**Comment by Phi-Hung-1007** [comment]
So why can't I still use dontBreakRows for rowSpan like in the example above?

**Comment by fe-cj** [comment]
`dontBreakRows` applies to single rows, not to rowspanned rows.

**Comment by Phi-Hung-1007** [comment]
Oh I thought I fixed the dontBreakRows with rowSpan error in the above issue. But when I updated to version 0.2.13 I couldn't even call dontBreakRows with single row because of the error in the first comment.
Ảnh chụp màn hình 2024-09-29 065101

**Comment by fe-cj** [comment]
I fixed an error that was adding extra height to the table when combining `rowSpan` with `dontBreakRows`.

If you encounter a bug, it would be nice if you open an issue and share a doc definition that others can copy and paste in the playground.

**Comment by Phi-Hung-1007** [comment]
On the playground, I can't reproduce the error I get in IDE when installing version 0.2.13 and calling dontBreakRows: true
On the Playground: 
image
On my IDE: 
image

**Comment by liborm85** [comment]
@Phi-Hung-1007 Again... If you found bug, open an issue with example code for reproduce problem runnable on playground or  https://jsfiddle.net/ or a similar service, as is described in [CONTRIBUTING.md](https://github.com/bpampuch/pdfmake/blob/master/.github/CONTRIBUTING.md).
Screenshots are not runnable on playground.

**Pull request merged**
