### PR TITLE
Fixes #897 Anchor to section

### LINKED ISSUE #897: Anchor to section
Hi

Exist some way to create an internal anchor to pdf section? In example

```javascript
{
  text: 'Some awesome title',
  name: 'title1'
},
{
  text: 'Anchor to title',
  link: '#title1'
}
```

### PR DESCRIPTION
**Pull request by marc0l92**
# Fixes #897 Anchor to section

Add the feature to create internal anchors to PDF sections using the following structure:

```
{
  text: 'Some awesome title',
  id: 'title1'
},
{
  text: 'Anchor to title',
  anchor: 'title1'
}
```

I used the property `id` for the destination object because it was already implemented for the `textReference` feature.

This feature creates links to the page where the destination object is located, not to the text line.

### CODE REVIEW

**Comment by drager** [comment]
@bpampuch @liborm85: Any reason this isn't merged?

**Comment by filippomuscolino** [comment]
Any updates on this?

**Comment by TonD83** [comment]
I know it's almost 1,5 years later, but I'm wondering if why this is still open? Would really love to have this feature so I can use pdfmake for our needs.

**Comment by marc0l92** [comment]
If you really need it you can add my fork as a new remote and cherry-pick the commits... Then I don't know how to push for the review and merge

**Comment by liborm85** [comment]
I'm waiting to merge issue https://github.com/foliojs/pdfkit/pull/720, where is redirected to specific text (not only to page number).

**Comment by liborm85** [comment]
Implemented in pdfmake: https://github.com/bpampuch/pdfmake/issues/897#issuecomment-484776044

**Pull request closed without merging**
