### PR TITLE
Add ability to turn text into a link

### PR DESCRIPTION
**Pull request by astarr**
Add links to PDF by doing this: { text:"Google", link:"http://www.google.com", decoration:"underline" }

### CODE REVIEW

**Comment by nfroidure** [comment]
+1

**Comment by ymkins** [comment]
+1 and there is the issue https://github.com/bpampuch/pdfmake/issues/37

**Comment by bpampuch** [comment]
thx

**Comment by tonipenya** [comment]
In version 0.1.20, {text: 'http://www.example.com'} results in a link in the PDF file. However, { text:"Google", link:"http://www.google.com", decoration:"underline" } as suggested by @astarr does not.
Am I missing something?

**Comment by athavanraja** [comment]
@tonipenya 

I am having the same issue as yours. did you find a solution?

Thanks.
Raja

**Comment by athavanraja** [comment]
further investigation reveals that buildinlines is omitting link attribute. Working on, will update.

**Comment by athavanraja** [comment]
made the following change in pdfmake.js to make it work.

	var data = this.textTools.buildInlines(node.text, styleStack); 
// new code after the above line . (line no. 15795)
       // added by raja
       if(node.link)
       {
      for(var di = 0, dl = data.items.length; di < dl; di++) {
             data.items[di].link = node.link ;
       }
       }
       //  end of addition

Regards
Raja

**Pull request merged**
