### PR TITLE
Watermark improvements

### PR DESCRIPTION
**Pull request by liborm85**

### CODE REVIEW

**Comment by goxr3plus** [comment]
Can we change the angle of the watermark with this change :) ? @liborm85

**Comment by liborm85** [comment]
Yes.

**Comment by goxr3plus** [comment]
I forked this repository and i will add you changes and publish it to npm with name `pdfmake2` so i can use your improvements until they get merged . So how can i use your changes in the below example ? 

`watermark: { text: "Watermark", color: "gray", opacity: 0.3, bold: true, alignment: "center" }`

**Comment by goxr3plus** [comment]
MERGARE TO το θέλει ο OPAP !

**Comment by goxr3plus** [comment]
Excellent :) , can we have an example of how to use it :) ?

```JAVA
watermark: { text: "Watermark", color: "gray", opacity: 0.3, bold: true, alignment: "center" }
```

For example on the above . @liborm85

**Comment by liborm85** [comment]
see [upcoming documentation](https://github.com/pdfmake/docs/blob/master/content/document-definition-object/watermark.md)

**Comment by alham28** [comment]
can we add watermark in 2 lines ? @liborm85

**Pull request merged**
