### PR TITLE
Allow oversized images if they are the only item on a page

### LINKED ISSUE #855: Empty PDF generated for large image
Attached image is generated by html2canvas and I am trying to save it as PDF. But pdf is gerating empty document with two pages. 

Can any one help to solve this?

download

 html2canvas(document.getElementById("myTable"), {
            onrendered: function (canvas) { 
                var data = canvas.toDataURL(); 
                var docDefinition = {
                    content: [{
                        image: data
                    }]
                };
                pdfMake.createPdf(docDefinition).download("Consolidated_Transcript.pdf");
            }
        });

### PR DESCRIPTION
**Pull request by wilsaj**
This should fix #855 - an issue where blank pages are rendered if an image can not fit vertically on a page. If the page is empty, it will add the oversized image. If there is anything already on the page, it will add add a new page containing the oversized image.

### CODE REVIEW

**Comment by liborm85** [comment]
Thanks.

**Comment by wilsaj** [comment]
Thanks for merging.

Do you have an estimate on when the next release will go out? This will fix some issues for us downstream and I'm trying to decide whether to wait for release or set up a temporarily vendor'd version with the fix.

**Comment by liborm85** [comment]
New version released.

**Comment by wilsaj** [comment]
Awesome, thanks!

**Pull request merged**
