### PR TITLE
FileSaver.js Fix

### PR DESCRIPTION
**Pull request by var-bin**
Hi @bpampuch,

I've got a problem with [file-saver](https://github.com/eligrey/FileSaver.js) third-party library. Unfortunately it doesn't clone at all with whole repo. So I decided to add this library as `devDependencies` in `package.json`. I think this approach is more appropriate in this instance.

Fixes list:
- Install [file-saver](https://github.com/eligrey/FileSaver.js)
- Replace `var FileSaver = require('../../libs/FileSaver.js/FileSaver');` -> `var FileSaver = require('file-saver');` for more info, please follow [this link](http://take.ms/iRVZB)
- Sorted `package.json`
- Fix some typos

### CODE REVIEW

**Comment by var-bin** [comment]
Hi @liborm85,

Sorry for my interrupt, could you help me with this PR?

**Comment by liborm85** [comment]
Cloning from git works well without problem, but we can probably refactor it, let's have it consistent acquiring dependencies. It is possible to change from git submodule to dev dependency, it should not break anything.

Merged. Thanks.

**Comment by var-bin** [comment]
Hi @liborm85,

Thank you for your response. I don't know which step I do wrong but when I cloning repo and try to run `npm run build` I got the error what I mentioned earlier. I agree with your comment according to **"but we can probably refactor it, let's have it consistent acquiring dependencies"**. 

BTW, thank you very much for your time and assistance in this matter.

Best regards,
Vitalii

**Comment by liborm85** [comment]
Clone with submodules is something like this:
```
git clone https://github.com/bpampuch/pdfmake.git
cd pdfmake
git submodule update --init --recursive
```

**Comment by var-bin** [comment]
I think this is not a good idea to add one more step for starting to work with the project in `dev` mode. The better way is:

```bash
git clone https://github.com/bpampuch/pdfmake.git
cd pdfmake
npm i
```
This command is useless:
`git submodule update --init  libs/FileSaver.js`

I forgot to fix `README.md`. I will do it immediately in new PR

**Pull request merged**
