### PR TITLE
Table height

### PR DESCRIPTION
**Pull request by touchaqb**
Pull request based on strokovnjaka commit (98b13a6a18dbba1e42476573f4bd7e3c0757e279) with some corrections and enhancements.

It aims to solve issues: #264, #391 and #995. Because the issues are somehow correlated, so are the implementations, that is why they are in the same branch.

Please let me know if there is something to change.

### CODE REVIEW

**Comment by liborm85** [comment]
Thanks. Please add some example of use to [examples/tables.js](https://github.com/bpampuch/pdfmake/blob/master/examples/tables.js) file.

**Comment by varundbest** [comment]
So, #995 is fixed? I've been waiting for this PR for quite a while now! Great Job man!

**Comment by liborm85** [comment]
I tested it, but how this PR solve issues https://github.com/bpampuch/pdfmake/issues/264 and https://github.com/bpampuch/pdfmake/issues/995. I see no difference.

**Comment by varundbest** [comment]
For me it solved #995.

**Comment by liborm85** [comment]
@varundbest I it tested with example from issue #995, but get same wrong result, screenshot:
screen-995

Where is fix?

**Comment by varundbest** [comment]
He have implemented my suggested changes from #995, over here :- https://github.com/bpampuch/pdfmake/pull/1056/commits/5db472c274b9a28114bbf0f03b0f9f6f21e6e53c#diff-a6971eb7756728d7e5b095b6fa3bbec3
Perhaps there is a bug in the implementation. Reason for #995 (AFAIK) :- 
https://github.com/bpampuch/pdfmake/issues/385#issuecomment-310605661

**Comment by liborm85** [comment]
@touchaqb ping

**Comment by Tonio31** [comment]
Any news on this ?

**Comment by liborm85** [comment]
No reaction => Close

**Pull request closed without merging**
