### PR TITLE
Added leading indent

### PR DESCRIPTION
**Pull request by Prevole**
Added the possibility to add a leading indent to do:

```
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget tempor 
mi. Ut cursus velit iaculis, posuere est eu, suscipit diam. Vivamus sed dui 
convallis, ultrices nulla quis, molestie velit. Proin consectetur accumsan eros. 
  Nunc in efficitur sem. Donec sit amet ultricies lorem, at feugiat ligula. Aliquam 
erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
posuere cubilia Curae; Nam tristique justo eu blandit semper. 
  Proin pharetra eros magna, nec placerat felis aliquam sed. Fusce varius 
mauris vel est scelerisque gravida. Morbi tortor ante, egestas in tortor eu, 
iaculis ultrices tellus. 
```

### CODE REVIEW

**Comment by liborm85** [comment]
Merged. Thanks.

**Comment by Meirimbr** [comment]
How do I implement the indent? Could you show me an example? Thank you

**Comment by Prevole** [comment]
@Meirimbr : You can simply add the option `leadingIndent: 20` in a style block. Then apply it to your paragraphs.

```javascript
{
	content: [{
		    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius.',
		    style: 'lead'
	}],
	styles: {
		lead: {
		    leadingIndent: 20
		}
	}
}
```

**Comment by thaddeusm** [comment]
I have a unique use case where I basically need this functionality inverted.  I would like to indent every line except for the first in a paragraph/wrapped text content.  Any ideas?

**Comment by pibubear** [comment]
@thaddeusm How do I implement leadingIndent functionality with negative value in order to apply indentation after the provided text? Could you show me an example? I'm trying to do this with inner tables using html-to-pdf module.
Thank you

**Comment by thaddeusm** [comment]
> @thaddeusm How do I implement leadingIndent functionality with negative value in order to apply indentation after the provided text? Could you show me an example? I'm trying to do this with inner tables using html-to-pdf module.
> Thank you

In my use case (creating a PDF in APA Style), I need to indent every line but the first in a reference entry. I accomplished this by using a negative leadingIndent value to nullify a left margin value:

```javascript
...
referenceEntry: {
    leadingIndent: -36,
    margin: [36, 0, 0, 0]
}
```

**Pull request merged**
